# Generated by Django 4.2.27 on 2026-02-19 17:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('menu_image', cloudinary.models.CloudinaryField(default='placeholder_menu', max_length=255, verbose_name='image')),
            ],
        ),
    ]
