# Generated by Django 4.2.27 on 2026-02-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websiteimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteImage',
        ),
    ]
