# Generated by Django 4.2.27 on 2026-02-18 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_info',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking_info',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking_info',
            name='booking_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
