# Generated by Django 4.2.27 on 2026-02-19 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0002_remove_booking_info_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_info',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 19, 16, 11, 19, 122684, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking_info',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
