# Generated by Django 4.2.27 on 2026-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0003_alter_booking_info_booking_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_info',
            name='booking_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking_info',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
