# Generated by Django 4.2.27 on 2026-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0004_alter_booking_info_booking_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_info',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
